---
- name: Create a VM on Proxmox
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Create VM with 1 10GB SATA disk and an EFI disk, with Secure Boot disabled by default
      community.general.proxmox_kvm:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id | default(omit) }}"
        api_token_secret: "{{ api_token_secret | default(omit) }}"

        node: prox-host-01
        name: test-vm

        sockets: 1
        cores: 1
        vcpus: 2

        memory: 2048

        scsi0:
          storage: prox-storage
          size: 10G
          format: raw

        bios: ovmf
        efidisk0:
          storage: prox-storage
          format: raw
          efitype: 4m
          pre_enrolled_keys: false
        tpmstate:
          storage: prox-storage
          version: 2.0
        localtime: true


 



    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play

  "msg": "Unsupported parameters for (community.general.proxmox_kvm) module: scsih0, tpmstate. 
  Supported parameters include: 
      acpi, agent, 
      api_host, api_password, api_port, api_token_id, api_token_secret, api_user, 
      archive, args, audio, autostart, 
      balloon, bios, boot, bootdisk, 
      cicustom, cipassword, citype, ciupgrade, ciuser, clone, cores, cpu, cpulimit, cpuunits, 
      delete, description, digest, 
      efidisk0, force, format, freeze, full, 
      hookscript, hostpci, hotplug, hugepages, 
      ide, ipconfig, keyboard, kvm, localtime, lock, 
      machine, memory, migrate, migrate_downtime, migrate_speed, 
      name, nameservers, net, newid, node, numa, numa_enabled, 
      onboot, ostype, parallel, pool, protection, 
      reboot, revert, 
      sata, scsi, scsihw, searchdomains, serial, shares, skiplock, 
      smbios, snapname, sockets, sshkeys, startdate, startup, state, storage, 
      tablet, tags, target, tdf, template, timeout, tpmstate0, 
      update, update_unsafe, usb, 
      validate_certs, vcpus, vga, virtio, vmid, 
      watchdog.",