---
- name: Create a VM on Proxmox v2.1
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Map survey input to Proxmox-compatible ostype
      ansible.builtin.set_fact:
        ostype_map:
          "Windows 11/2022/2025": win11
          "Windows 10/2016/2019": win10
          "Windows 8.x/2012/2012r2": win8
          "Windows 7/2008r2": win7
          "Windows XP/2003": w2k3
          "Linux6x": l26

    - name: Extract proxmox-compatible ostype
      ansible.builtin.set_fact:
        ostype_code: "{{ ostype_map[ostype] }}"

    - name: Creating a VM based on Survey Anwers
      community.general.proxmox_kvm:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id | default(omit) }}"
        api_token_secret: "{{ api_token_secret | default(omit) }}"
        node: "{{ node }}"
        vmid: "{{ vmid }}"
        name: "{{ vm_name }}"
        bios: ovmf
        efidisk0:
          storage: prox-storage
          format: raw
          efitype: 4m
          pre_enrolled_keys: false
        tpmstate0:
          storage: prox-storage
          version: 2.0
        cores: "{{ cores }}"
        sockets: "{{ sockets }}"
        cpu: host
        memory: "{{ memory }}"
        scsi:
          scsi0: "prox-storage:{{ disk_size }},format=raw,cache=writeback,discard=on"
        scsihw: virtio-scsi-pci
        boot: c
        ostype: "{{ ostype_code }}"
        net:
          net0: 'virtio,bridge=vmbr0,queues=8,tag=66'
        onboot: true
        agent: 1
      delegate_to: localhost
 
    - name: Timmay HARD STOP this Playbook
      ansible.builtin.meta: end_play
