---
- name: Retrieve list of Proxmox VMs
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Gather Proxmox VM info
      community.general.proxmox_vm_info:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "prox-host-01"
      register: result

    - name: Print all VMs
      ansible.builtin.debug:
        var: result.vms